# Generated by Django 3.2.8 on 2022-04-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosultant_payment',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
