# Generated by Django 3.2.8 on 2021-11-20 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0002_teacher_time_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_time',
            old_name='date_from',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='teacher_time',
            name='date_to',
        ),
        migrations.AddField(
            model_name='teacher_time',
            name='from_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_time',
            name='to_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
