# Generated by Django 3.2.8 on 2021-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0003_auto_20211120_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_time',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
