# Generated by Django 3.2.8 on 2022-01-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0003_teacher_time_recurrences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_time',
            name='recurrences',
        ),
    ]
