# Generated by Django 3.2.8 on 2022-02-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0003_alter_cosultant_payment_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosultant_payment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
