# Generated by Django 3.2.8 on 2022-02-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0004_cosultant_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosultant_payment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
