# Generated by Django 3.2.8 on 2021-11-20 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0004_teacher_time_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosultant_payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
