# Generated by Django 3.2.8 on 2022-01-11 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0004_remove_teacher_time_recurrences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_time',
            old_name='date',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='teacher_time',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
