# Generated by Django 3.2.8 on 2022-03-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0005_alter_cosultant_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosultant_payment',
            name='method',
            field=models.CharField(choices=[('bank', 'bank'), ('Western Union', 'Western Union'), ('Paypal', 'Paypal')], max_length=50),
        ),
    ]
