# Generated by Django 3.2.8 on 2021-11-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0005_cosultant_payment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='pending',
        ),
        migrations.AddField(
            model_name='cosultant_payment',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
