# Generated by Django 3.2.8 on 2022-01-12 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0005_auto_20220111_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosultant_payment',
            name='consult',
        ),
        migrations.AddField(
            model_name='cosultant_payment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Consultant.teacher_time'),
        ),
    ]
