# Generated by Django 3.2.8 on 2022-01-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0006_auto_20220112_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_time',
            old_name='from_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='teacher_time',
            name='to_date',
        ),
    ]
