# Generated by Django 3.2.8 on 2021-11-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0006_auto_20211121_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
