# Generated by Django 3.2.8 on 2021-11-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0007_consultant_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='zoom',
            field=models.TextField(blank=True),
        ),
    ]
