# Generated by Django 3.2.8 on 2022-01-12 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0007_auto_20220112_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_time',
            old_name='date',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='teacher_time',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='teacher_time',
            name='to_time',
        ),
        migrations.AddField(
            model_name='teacher_time',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
