# Generated by Django 3.2.8 on 2021-11-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0008_consultant_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosultant_payment',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
