# Generated by Django 3.2.8 on 2022-01-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0008_auto_20220112_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_time',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacher_time',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
