# Generated by Django 3.2.8 on 2021-12-01 00:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0009_cosultant_payment_ordered'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cosultant_payment',
            managers=[
                ('check_reject', django.db.models.manager.Manager()),
            ],
        ),
    ]
