# Generated by Django 3.2.8 on 2022-01-13 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0009_auto_20220112_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultant',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultant',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined'), ('started', 'started'), ('completed', 'completed')], default='pending', max_length=50),
        ),
    ]
