# Generated by Django 3.2.8 on 2021-12-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0010_alter_cosultant_payment_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='cosultant_payment',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cosultant_payment',
            name='pending',
        ),
        migrations.AddField(
            model_name='consultant',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined'), ('completed', 'completed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='cosultant_payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=50),
        ),
    ]
