# Generated by Django 3.2.8 on 2022-01-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0010_auto_20220113_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
