# Generated by Django 3.2.8 on 2022-01-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0011_auto_20220115_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='start_time',
        ),
    ]
