# Generated by Django 3.2.8 on 2021-12-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0011_auto_20211209_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='completed',
        ),
    ]
