# Generated by Django 3.2.8 on 2021-12-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0012_remove_consultant_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_time',
            name='date',
            field=models.DateField(),
        ),
    ]
