# Generated by Django 3.2.8 on 2021-12-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0013_alter_teacher_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_time',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
