# Generated by Django 3.2.8 on 2022-01-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0013_consultant_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_time',
            name='date',
            field=models.BooleanField(choices=[(1, 'Saturday'), (2, 'Sunday'), (3, 'Monday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher_time',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='teacher_time',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
