# Generated by Django 3.2.8 on 2021-12-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0014_alter_teacher_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_time',
            name='date',
            field=models.DateField(),
        ),
    ]
