# Generated by Django 3.2.8 on 2022-01-26 11:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0014_auto_20220126_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_time',
            name='date',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Saturday'), (2, 'Sunday'), (3, 'Monday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')], max_length=20, null=True),
        ),
    ]
