# Generated by Django 3.2.8 on 2022-01-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0016_auto_20211221_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosultant_payment',
            name='method',
            field=models.CharField(choices=[('Paymob', 'Paymob'), ('Western Union', 'Western Union'), ('Paypal', 'Paypal')], max_length=50),
        ),
    ]
