# Generated by Django 3.2.8 on 2022-01-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0018_alter_teacher_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_time',
            name='date',
            field=models.IntegerField(choices=[(1, 'Saturday'), (2, 'Sunday'), (3, 'Monday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')], default=1, max_length=20),
        ),
    ]
