# Generated by Django 3.2.8 on 2022-01-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0019_alter_teacher_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_time',
            name='date',
            field=models.IntegerField(choices=[(6, 'Saturday'), (7, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=1),
        ),
    ]
