# Generated by Django 3.2.8 on 2022-01-27 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0020_alter_teacher_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosultant_payment',
            name='data',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
