# Generated by Django 3.2.8 on 2022-01-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0023_userdataform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataform',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
