# Generated by Django 3.2.8 on 2022-01-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0026_alter_userdataform_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataform',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultant.teacher_time'),
        ),
    ]
