# Generated by Django 3.2.8 on 2022-01-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0028_auto_20220128_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='end_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
