# Generated by Django 3.2.8 on 2021-11-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
    ]
