# Generated by Django 3.2.8 on 2022-01-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_result',
            name='delivered',
        ),
        migrations.AddField(
            model_name='quiz_result',
            name='certification',
            field=models.CharField(choices=[('received', 'received'), ('pending', 'pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz_result',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('in-completed', 'in-completed')], default='in-completed', max_length=50),
        ),
    ]
