# Generated by Django 3.2.8 on 2022-01-21 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz', '0004_auto_20220121_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(choices=[('received', 'received'), ('pending', 'pending')], default='pending', max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_certification', to='Quiz.quiz_result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
