# Generated by Django 3.2.8 on 2021-11-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_auto_20211111_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
