# Generated by Django 3.2.8 on 2021-11-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_auto_20211112_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
    ]
