# Generated by Django 3.2.8 on 2021-11-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_auto_20211112_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answers',
            field=models.ManyToManyField(to='Quiz.Answers'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='Quiz.Question'),
        ),
    ]
