import os
from django.core.mail import send_mail,EmailMessage,get_connection

SUPPORT_EMAIL_HOST = os.environ['SUPPORT_EMAIL_HOST']
SUPPORT_EMAIL_USERNAME = os.environ['SUPPORT_EMAIL_USERNAME']
SUPPORT_EMAIL_PASSWORD = os.environ['SUPPORT_EMAIL_PASSWORD']
SUPPORT_EMAIL_PORT = os.environ['SUPPORT_EMAIL_PORT']
SUPPORT_MAIL_CONNECTION = get_connection(
host= SUPPORT_EMAIL_HOST, 
port=SUPPORT_EMAIL_PORT, 
username=SUPPORT_EMAIL_USERNAME, 
password=SUPPORT_EMAIL_PASSWORD, 
use_tls=False
) 
PAYMENT_EMAIL_USERNAME = os.environ['PAYMENT_EMAIL_USERNAME']
PAYMENT_EMAIL_PASSWORD = os.environ['PAYMENT_EMAIL_PASSWORD']
PAYMENT_EMAIL_PORT = os.environ['PAYMENT_EMAIL_PORT']
PAYMENT_MAIL_CONNECTION = get_connection(
host= SUPPORT_EMAIL_HOST, 
port=PAYMENT_EMAIL_PORT,  
username=PAYMENT_EMAIL_USERNAME, 
password=PAYMENT_EMAIL_PASSWORD, 
use_tls=False    
) 
TASK_NOTIFICATION_EMAIL_USERNAME=os.environ['TASK_NOTIFICATION_EMAIL_USERNAME']
TASK_NOTIFICATION_EMAIL_PASSWORD=os.environ['TASK_NOTIFICATION_EMAIL_PASSWORD']
TASK_NOTIFICATION_EMAIL_HOST=os.environ["TASK_NOTIFICATION_EMAIL_HOST"]
TASK_NOTIFICATION_EMAIL_PORT=os.environ["TASK_NOTIFICATION_EMAIL_PORT"]
TASK_NOTIFICATION_EMAIL_CONNECTION=get_connection(
host= TASK_NOTIFICATION_EMAIL_HOST, 
port=TASK_NOTIFICATION_EMAIL_PORT, 
username=TASK_NOTIFICATION_EMAIL_USERNAME, 
password=TASK_NOTIFICATION_EMAIL_PASSWORD, 
use_tls=False
)
DASHBOARD_EMAIL_HOST = os.environ['DASHBOARD_EMAIL_HOST']
DASHBOARD_EMAIL_USERNAME = os.environ['DASHBOARD_EMAIL_USERNAME']
DASHBOARD_EMAIL_PASSWORD = os.environ['DASHBOARD_EMAIL_PASSWORD']
DASHBOARD_EMAIL_PORT = os.environ['DASHBOARD_EMAIL_PORT']
DASHBOARD_MAIL_CONNECTION = get_connection(
host= DASHBOARD_EMAIL_HOST, 
port=DASHBOARD_EMAIL_PORT, 
username=DASHBOARD_EMAIL_USERNAME, 
password=DASHBOARD_EMAIL_PASSWORD, 
use_tls=False
)  
FINANCE_EMAIL_USERNAME=os.environ["FINANCE_EMAIL_USERNAME"]
def send_mail_approve(request,user,body,subject):
    msg = EmailMessage(
        subject=subject,
        body=body,
        from_email=DASHBOARD_EMAIL_USERNAME,
        to=[TASK_NOTIFICATION_EMAIL_USERNAME],
        reply_to=[user],
        connection=DASHBOARD_MAIL_CONNECTION
        )
    msg.content_subtype = "html"  # Main content is now text/html
    msg.send()
    return True

