# Generated by Django 3.2.8 on 2021-11-17 01:50

import Blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.CreateModel(
            name='Blog_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Blogs.models.upload_blog_images)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ManyToManyField(related_name='blog_comment', to='Blogs.Blog_Images'),
        ),
    ]
