# Generated by Django 3.2.8 on 2022-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='domain_type',
            field=models.IntegerField(choices=[(1, 'agartha'), (2, 'kemet')], default=1),
        ),
    ]
