# Generated by Django 3.2.8 on 2022-01-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
