# Generated by Django 3.2.8 on 2021-11-17 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_images',
            name='blog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Blogs.blog'),
        ),
    ]
