# Generated by Django 3.2.8 on 2022-01-24 22:31

import Blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_alter_blog_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to=Blogs.models.upload_blog_videos),
        ),
    ]
