# Generated by Django 3.2.8 on 2022-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_category_domain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='type',
            field=models.IntegerField(choices=[(1, 'agartha'), (2, 'kemet')], default=1),
        ),
    ]
