# Generated by Django 3.2.8 on 2021-11-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_alter_blog_images_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='blog_comment', to='Blogs.Blog_Images'),
        ),
        migrations.AlterField(
            model_name='blog_images',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.blog'),
        ),
    ]
