# Generated by Django 3.2.8 on 2022-03-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_prices_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_payment',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
