# Generated by Django 3.2.8 on 2022-01-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_alter_blog_video'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
            ],
        ),
    ]
