# Generated by Django 3.2.8 on 2021-11-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
