# Generated by Django 3.2.8 on 2022-01-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_alter_blog_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined'), ('refund', 'refund')], default='pending', max_length=50),
        ),
    ]
