# Generated by Django 3.2.8 on 2022-03-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_blog_payment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_payment',
            name='type',
            field=models.IntegerField(choices=[(1, 'agartha'), (2, 'kemet')], default=1),
        ),
    ]
