# Generated by Django 3.2.8 on 2021-11-17 18:47

import Blogs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blogs', '0007_blog_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Blog_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Bank Transaction', 'Bank Transaction'), ('Western Union', 'Western Union'), ('Vodafone Cash', 'Vodafone Cash'), ('Paypal', 'Paypal')], max_length=50)),
                ('payment_image', models.ImageField(null=True, upload_to=Blogs.models.upload_blog_payment)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('transaction_number', models.CharField(max_length=50, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('expired_at', models.DateField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
