# Generated by Django 3.2.8 on 2021-11-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0009_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_payment',
            name='phone',
        ),
    ]
