# Generated by Django 3.2.8 on 2021-11-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0010_remove_blog_payment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_payment',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
