# Generated by Django 3.2.8 on 2021-11-21 22:31

import Blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0011_blog_payment_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_payment',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to=Blogs.models.upload_blog_payment),
        ),
    ]
