# Generated by Django 3.2.8 on 2021-11-30 11:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0012_alter_blog_payment_payment_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('checss', django.db.models.manager.Manager()),
            ],
        ),
    ]
