# Generated by Django 3.2.8 on 2021-11-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0014_alter_blog_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
            ],
        ),
    ]
