# Generated by Django 3.2.8 on 2021-12-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0017_blog_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
