# Generated by Django 3.2.8 on 2021-12-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0018_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_payment',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='blog_payment',
            name='pending',
        ),
        migrations.AddField(
            model_name='blog_payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=50),
        ),
    ]
