# Generated by Django 3.2.8 on 2021-12-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0019_auto_20211209_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='approved',
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=50),
        ),
    ]
