# Generated by Django 3.2 on 2022-04-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunds',
            name='type',
            field=models.CharField(choices=[('course_payment', 'course_payment'), ('consultant_payment', 'consultant_payment'), ('blog_payment', 'blog_payment'), ('movie_payment', 'movie_payment'), ('music_payment', 'music_payment'), ('audio_book_payment', 'audio_book_payment'), ('e_book_payment', 'e_book_payment')], max_length=50),
        ),
    ]
