# Generated by Django 3.2.8 on 2022-02-03 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='data',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refunds',
            name='type',
            field=models.CharField(choices=[('course_payment', 'course_payment'), ('consultant_payment', 'consultant_payment')], max_length=50),
        ),
    ]
