# Generated by Django 3.2.8 on 2021-12-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_addstudentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejects',
            name='type',
            field=models.CharField(choices=[('course', 'course'), ('blogs', 'blogs'), ('blog_payment', 'blog_payment'), ('consultant_payment', 'consultant_payment'), ('events', 'events'), ('payment', 'payment'), ('teacher', 'teacher'), ('add_user', 'add_user')], max_length=50),
        ),
    ]
