# Generated by Django 3.2.8 on 2022-01-30 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20220129_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='refunds',
            name='transaction_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
