# Generated by Django 3.2.8 on 2022-01-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20220130_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunds',
            name='type',
            field=models.CharField(choices=[('course_payment', 'course_payment'), ('blog_payment', 'blog_payment'), ('consultant_payment', 'consultant_payment')], max_length=50),
        ),
    ]
