# Generated by Django 3.2.8 on 2022-02-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
