# Generated by Django 3.2.8 on 2022-03-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunds',
            name='type',
            field=models.CharField(choices=[('course_payment', 'course_payment'), ('consultant_payment', 'consultant_payment'), ('blog_payment', 'blog_payment'), ('movie_payment', 'movie_payment')], max_length=50),
        ),
    ]
