# Generated by Django 3.2.8 on 2022-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alter_refunds_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunds',
            name='type',
            field=models.CharField(choices=[('course_payment', 'course_payment'), ('consultant_payment', 'consultant_payment'), ('blog_payment', 'blog_payment'), ('movie_payment', 'movie_payment'), ('music_refund', 'music_refund')], max_length=50),
        ),
    ]
