# Generated by Django 3.2.8 on 2022-01-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
