# Generated by Django 3.2.4 on 2021-10-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211012_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[(1, 'student'), (2, 'teacher')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
