# Generated by Django 3.2.8 on 2022-01-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220108_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherforms',
            name='code',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_image',
            field=models.ImageField(blank=True, default='https://garthaacademy.b-cdn.net/default_image/male.jpg', null=True, upload_to=''),
        ),
    ]
