# Generated by Django 3.2.4 on 2021-10-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=20),
        ),
    ]
