# Generated by Django 3.2.8 on 2022-01-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220108_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_image',
            field=models.ImageField(blank=True, default='https://agarthaacademy.b-cdn.net/default_image/male.jpg', null=True, upload_to=''),
        ),
    ]
