# Generated by Django 3.2.8 on 2022-03-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kemet_vip',
            field=models.BooleanField(default=False),
        ),
    ]
