# Generated by Django 3.2.8 on 2021-11-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
