# Generated by Django 3.2.8 on 2021-11-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
    ]
