# Generated by Django 3.2.8 on 2021-12-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_is_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='account_image',
        ),
    ]
