# Generated by Django 3.2.8 on 2021-12-07 21:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_image_user_account_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacherforms',
            managers=[
                ('check_reject', django.db.models.manager.Manager()),
            ],
        ),
    ]
