# Generated by Django 3.2.8 on 2021-12-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_teacherforms_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacherforms',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='teacherforms',
            old_name='approved',
            new_name='status',
        ),
    ]
