# Generated by Django 3.2.8 on 2021-12-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20211226_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherforms',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=50),
        ),
    ]
