# Generated by Django 3.2.8 on 2022-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_a', models.TextField(null=True)),
                ('text_r', models.TextField(null=True)),
            ],
        ),
    ]
