# Generated by Django 3.2.8 on 2022-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_auto_20220109_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='text_en',
            field=models.TextField(null=True),
        ),
    ]
