# Generated by Django 3.2 on 2022-04-23 13:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='name_ar',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='name_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
