# Generated by Django 3.2 on 2022-04-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_auto_20220423_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Frontend.branch'),
        ),
    ]
