# Generated by Django 3.2.8 on 2021-11-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='map',
        ),
    ]
