# Generated by Django 3.2.8 on 2022-01-18 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_suppot_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suppot_Email',
            new_name='Support_Email',
        ),
    ]
