# Generated by Django 3.2.4 on 2021-10-14 22:30

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211015_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(default=1, upload_to=home.models.upload_course_videos),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
