# Generated by Django 3.2.8 on 2021-11-21 10:54

from django.db import migrations
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211121_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
