# Generated by Django 3.2.4 on 2021-10-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211015_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('on process', 'on process'), ('complete', 'complete')], max_length=50),
        ),
    ]
