# Generated by Django 3.2.8 on 2022-02-02 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='watched_users',
            field=models.ManyToManyField(blank=True, related_name='watched_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
