# Generated by Django 3.2.4 on 2021-10-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_course_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='course_reviews', to='home.Reviews'),
        ),
    ]
