# Generated by Django 3.2.8 on 2022-02-02 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_videos_watched_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='watched_users',
            field=models.ManyToManyField(blank=True, related_name='watched_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
