# Generated by Django 3.2.8 on 2022-02-14 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_videos_watched_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='expired_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
