# Generated by Django 3.2.4 on 2021-10-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_course_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='asdsad',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
