# Generated by Django 3.2.8 on 2021-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211121_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
