# Generated by Django 3.2.8 on 2022-03-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220214_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='domain_type',
            field=models.IntegerField(choices=[(1, 'agartha'), (2, 'kemet')], default=1),
        ),
    ]
