# Generated by Django 3.2.8 on 2021-11-24 20:22

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_payment_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to=home.models.upload_course_videos),
        ),
    ]
