# Generated by Django 3.2.4 on 2021-10-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_course_asdsad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='asdsad',
        ),
    ]
