# Generated by Django 3.2.8 on 2021-11-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211124_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
