# Generated by Django 3.2.8 on 2021-11-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_events_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
