# Generated by Django 3.2.8 on 2021-11-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20211125_2337'),
        ('home', '0011_news_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz.quiz'),
        ),
    ]
