# Generated by Django 3.2.8 on 2021-10-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='my_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='home.course'),
            preserve_default=False,
        ),
    ]
