# Generated by Django 3.2.8 on 2021-11-29 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211126_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.branch'),
        ),
    ]
