# Generated by Django 3.2.8 on 2021-12-01 10:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_events_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('check_reject', django.db.models.manager.Manager()),
            ],
        ),
    ]
