# Generated by Django 3.2.8 on 2021-10-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_videos_my_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
