# Generated by Django 3.2.8 on 2021-10-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_videos_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
