# Generated by Django 3.2.8 on 2021-12-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_course_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('hold', 'hold'), ('start', 'start')], default='hold', max_length=20),
        ),
    ]
