# Generated by Django 3.2.8 on 2021-12-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_events_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('hold', 'hold'), ('start', 'start'), ('end', 'end')], default='hold', max_length=20),
        ),
    ]
