# Generated by Django 3.2.8 on 2021-10-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_videos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
