# Generated by Django 3.2.8 on 2021-12-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_events_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pending',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=50),
        ),
    ]
