# Generated by Django 3.2.8 on 2021-12-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_news_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='approved',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=50),
        ),
    ]
