# Generated by Django 3.2.8 on 2021-10-19 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_auto_20211019_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(default=1, upload_to=home.models.upload_events_images),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='event_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
