# Generated by Django 3.2.8 on 2021-12-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_events_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='events',
            name='expired',
        ),
    ]
