# Generated by Django 3.2.8 on 2021-10-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211019_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
