# Generated by Django 3.2.8 on 2021-12-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_events_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.URLField(),
        ),
    ]
