# Generated by Django 3.2.8 on 2021-12-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_videos_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='video',
            new_name='video_url',
        ),
    ]
