# Generated by Django 3.2.8 on 2021-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_teacher_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='period',
        ),
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, to='home.Videos'),
        ),
    ]
