# Generated by Django 3.2.8 on 2021-12-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_course_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_uid',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
