# Generated by Django 3.2.8 on 2021-12-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
