# Generated by Django 3.2.8 on 2022-01-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20211218_1747'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payment',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Paymob', 'Paymob'), ('Western Union', 'Western Union'), ('Paypal', 'Paypal')], max_length=50),
        ),
    ]
