# Generated by Django 3.2.8 on 2021-10-27 14:46

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to=home.models.upload_blog_images),
            preserve_default=False,
        ),
    ]
