# Generated by Django 3.2.8 on 2021-10-27 20:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
