# Generated by Django 3.2.8 on 2021-10-27 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0037_alter_blog_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Comment_Rpely',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_reply', to='home.blog')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blog_comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
