# Generated by Django 3.2.8 on 2021-10-27 22:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0038_blog_comment_rpely'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Comment_Rpely',
            new_name='Blog_Comment_Reply',
        ),
    ]
