# Generated by Django 3.2.8 on 2021-10-30 21:01

from django.db import migrations, models
import protected_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20211028_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to='uploads/')),
            ],
        ),
    ]
