# Generated by Django 3.2.8 on 2021-10-30 21:25

from django.db import migrations
import home.models
import protected_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to=home.models.upload_course_videos),
        ),
    ]
