# Generated by Django 3.2.8 on 2021-10-31 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0042_alter_videos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='visits',
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to=home.models.upload_course_videos),
        ),
        migrations.AddField(
            model_name='blog_views',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_viewers', to='home.blog'),
        ),
        migrations.AddField(
            model_name='blog_views',
            name='viewers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
