# Generated by Django 3.2.8 on 2021-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
