# Generated by Django 3.2.8 on 2021-11-02 20:00

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_payment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Bank Transaction', 'Bank Transaction'), ('Western Union', 'Western Union'), ('Vodafone Cash', 'Vodafone Cash')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_image',
            field=models.ImageField(null=True, upload_to=home.models.upload_payment_images),
        ),
    ]
