# Generated by Django 3.2.8 on 2021-11-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20211102_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Bank Transaction', 'Bank Transaction'), ('Western Union', 'Western Union'), ('Vodafone Cash', 'Vodafone Cash'), ('Paypal', 'Paypal')], max_length=50),
        ),
    ]
