# Generated by Django 3.2.8 on 2021-11-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_remove_quiz_course'),
        ('home', '0049_alter_payment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz'),
        ),
    ]
